### ISSUE TITLE
Wrong crosssell and upsell templates of second Tweakwise environment

### ISSUE THREAD

**Issue by JSeverein** [EmicoEcommerce/Magento2Tweakwise#11]
Issue Brief
We have a Magento 2 environment that has multiple store views. Each store view uses their own Tweakwise Environment and therefor a different Catalog / Tweakwise / General / Authentication Key in the admin.

When we go to the second store view level in the admin, then we see the different authentication key. But when we scroll down to Catalog / Tweakwise / Default Crosssell template and Default Upsell template then we see the templates of our other storeview.

So we believe the wrong authentication key is used when loading these templates. Possibly the one that's set on the default level.

Environment
PHP Version: (5.6|7.0|7.1)
Magento Version: 2.4.2-p2
Tweakwise Version: v3.3.8
Tweakwise Export Version: v2.1.0
Magento Deploy Mode: production
Steps to reproduce
Have two store views in Magento 2 en two environments in Tweakwise.
Set default and first store view Tweakwise authentication key to key number 1
Set second store view Tweakwise authentication to key number 2
Attempt to select crosssell and upsell templates under Catalog / Tweakwise / Default Crosssell template and Default Upsell template
Actual result
On default and both store view levels the selects show only the templates of environment number 1.

Expected result
On the default and first store view level, we expect to see templates of environment number 1.
On the second store view level, we expect to see templates of environment number 2.

This was previously reported here https://github.com/EmicoEcommerce/Magento2Tweakwise/issues/258 but after updating it does not appear to be fixed.

**Comment by ahuininga-orisha** [comment]
It should already be fixed, but i will test it again.

In your environment data it states that your using tweakwise version 3.3.8. That doesn't seem correct, since the issue is fixed in v5.x

Can you check the actual version of the tweakwise extension your using?

**Comment by JSeverein** [comment]
Hi, oh yes sorry those versions are from the previous ticket. We are now using version 5.0.6, Magento 2.4.4-p2, Tweakwise export 5.0.2 and PHP8.1.

**Comment by ahuininga-orisha** [comment]
@JSeverein I can't seem to reproduce the issue in the latest version. Any change you can film it so I can see exactly the order you do this?

Also, when fixing this issue. There was an problem with caching the values of the cross/upsell templates. Can you check if you can clear the cache when you have the second store selected and then refreshing the page en checking if the values are then correct? So we know if it is an caching problem or not?

**Comment by JSeverein** [comment]
@ah-net I've send the video through WeTransfer to support@tweakwise.com. The issue still exists when clearing the cache and refreshing. It always uses the authentication key of the first store / the default level.

**Comment by ahuininga-orisha** [comment]
@JSeverein Thanks for the information. I've received the video. I'll try again and see if I can reproduce the issue.

**Comment by JSeverein** [comment]
@ah-net Hi, we've done some more debugging and found the issue. 

It does work correctly as you said when you view the templates on the lowest level aka store view. So if you select the store view, then the admin url ends with /store/4/ f.e. and the correct authentication key is used, because it can find the store parameter in $request. 

But when you select the website (one level higher, like we do in the video) then the url only contains f.e. /website/3/. And there is no store parameter. Then it still falls back to the default. 

Hope this helps, for now we at least have a workaround for our customer.

**Comment by ahuininga-orisha** [comment]
@JSeverein Thx, that would explain the issue. We will fix this so that is also works on website level
