### ISSUE TITLE
Response 404 after page reload when ajax filtering yes

### ISSUE THREAD

**Issue by agorbulin** [EmicoEcommerce/Magento2Tweakwise#321]
**Preconditions**

Last version of:
- tweakwise/magento2-attributelanding-tweakwise
- tweakwise/magento2-tweakwise-hyva
- tweakwise/magento2-tweakwise
- Ajax filtering = Yes

**STR:**
- visit POP 
- select 2 filters: gender, size
- make sure filter applied
- reload page
**ER:**
- page reloaded, filter applied
**AR:**
-page not found, response 404

**Possible workaround:** Ajax filtering = No

Please fix.

**Comment by ahuininga-orisha** [comment]
@agorbulin I need an little more information.

- Do you have an category suffix (if so what is it?) 
- Do you have the following setting enabled? emico_attributelanding/general/append_category_url_suffix

Workround disabeling emico_attributelanding/general/append_category_url_suffix should fix the the problem

**Comment by ahuininga-orisha** [comment]
@agorbulin 

https://github.com/EmicoEcommerce/Magento2AttributeLandingTweakwise/pull/48 may fix your problem. But only if the setting emico_attributelanding/general/append_category_url_suffix was the cause of the issue

**Comment by agorbulin** [comment]
Hi @ahuininga-orisha 

- indeed we have "catalog/seo/category_url_suffix" = "/"
- and disabled "emico_attributelanding/general/append_category_url_suffix" = null

I've tried to enable it by setting "emico_attributelanding/general/append_category_url_suffix" = 1, but problem was not solved.

**Comment by agorbulin** [comment]
@ahuininga-orisha 
I'm trying to apply the provided fix and inform you later. Thanks

**Comment by agorbulin** [comment]
@ahuininga-orisha 
Unfortunately the fix https://github.com/EmicoEcommerce/Magento2AttributeLandingTweakwise/pull/48/commits/c3d1ba1dba6baa3acdd388c8b13f806d59abcd42
does not help. I've tried with disabled and enabled "emico_attributelanding/general/append_category_url_suffix"

**Comment by ahuininga-orisha** [comment]
@agorbulin 

Then i'll check again if i can reproduce the issue with other settings. 

Can you provide an url example where it happens?

**Comment by agorbulin** [comment]
@ahuininga-orisha 
STR:
-visit POP https://www.noppies.com/en-en/baby-coat/
-select filter 'Gender' = 'boy' (or any)
-select filter 'Babykleding maat' = 50 (or any)
-reload page, F5
ER:
-filter applied
AR:
-404
**Notice:** there is not last version of module on prod, but I've tried the last one locally and still reproduce the problem

**Comment by ahuininga-orisha** [comment]
@agorbulin The problem seems to be the gender filter. Selecting an filter generates an url: https://www.noppies.com/nl-nl/baby-coat/babykleding_maatfilter/50/boy/

Which should be: https://www.noppies.com/en-en/baby-coat/boy/babykleding_maatfilter/50

So boy is added on the wrong place.

- Do you have custom code for the filters so that the gender/boy in the url is replaced by /boy or is that because they are all ALP's? 
- Can you provide an list with al the ALP urls with baby-coat in the url for one storeview/language?

**Comment by agorbulin** [comment]
@ahuininga-orisha 
No, I do not see '/nl-nl/' anyway in ajax responses on en-en website.
But you are right, after applying 2 filters URL should be
https://www.noppies.com/en-en/baby-coat/boy/babykleding_maatfilter/50/
instead of
https://www.noppies.com/en-en/baby-coat/babykleding_maatfilter/50/boy/
so, **/boy/** should be before size filter, but during ajax request somewhere moved forward. During the disabled ajax filtering, sequence is correct. Maybe you can point me where is this sorting could be?

**Comment by agorbulin** [comment]
@ahuininga-orisha 
Correct URL should be .../en-en/baby-coat/babykleding_maatfilter/44/hoofdgeslacht/boy/ (with hoofdgeslacht)
I've found a customization that removes 'hoofdgeslacht' from the URL, which is why the URL is broken.
Thank you for assist.
